### ISSUE TITLE
When using a single image UnboundLocalError: local variable 'full_frames' referenced before assignment

### ISSUE THREAD

**Issue by seranus** [Rudrabha/LipGAN#6]
When using a single image full_frames is not defined

`Traceback (most recent call last):
  File "batch_inference.py", line 228, in <module>
    main()
  File "batch_inference.py", line 178, in main
    print ("Number of frames to be used for inference: "+str(len(full_frames)))
UnboundLocalError: local variable 'full_frames' referenced before assignment`

Also FPS is a required parameter, in the docs for image it isn't specified

**Comment by prajwalkr** [comment]
I have fixed both the issues now. Please let me know if it is alright :)

**Comment by seranus** [comment]
It does not fix my main issues, you are defining full_frames only if the input is only a video

https://github.com/Rudrabha/LipGAN/blob/0cecae162e1ca19c8112d36ee46190143259f020/batch_inference.py#L166

but you are referencing it later for any input

https://github.com/Rudrabha/LipGAN/blob/0cecae162e1ca19c8112d36ee46190143259f020/batch_inference.py#L198

**Comment by prajwalkr** [comment]
Sorry about that. Defined full_frames for single image input as well. Any other errors?

**Comment by seranus** [comment]
It works now, what model goes into `--checkpoint` param it doesn't say in the param description. Is it the path to the LipGAN or I have to train a generator?

**Comment by prajwalkr** [comment]
Please indicate the line you are talking about.

**Comment by seranus** [comment]
Thanks, it works now. I was using the folder path instead of the LipGan file path --checkpoint
